### ISSUE TITLE
New version of chrome(40.0.2214.94 m), all previous versions worked fine: ArgumentError: Error #3735 	at global/C_Run::newThread()

### ISSUE THREAD

**Issue by CrossAlchemy** [crossbridge-community/crossbridge#75] opened 2015-02-05 13:55 UTC
ArgumentError: Error #3735
	at global/C_Run::newThread()
	at global/C_Run_J_3A__2F_adobe_2F_power_2F_cygwin_2F_tmp_2F_ccLFazKD_2E_lto_2E_bc_3A_5ea19223_2D_1599_2D_4f6d_2D_82b1_2D_d0cc48dd43f3::F_thr_new()
	at global/C_Run_J_3A__2F_adobe_2F_power_2F_cygwin_2F_tmp_2F_ccLFazKD_2E_lto_2E_bc_3A_5ea19223_2D_1599_2D_4f6d_2D_82b1_2D_d0cc48dd43f3::F__pthread_create()
	at global/C_Run_J_3A__2F_adobe_2F_power_2F_cygwin_2F_tmp_2F_ccLFazKD_2E_lto_2E_bc_3A_5ea19223_2D_1599_2D_4f6d_2D_82b1_2D_d0cc48dd43f3::F__ZN7CThread5StartEv()

**Comment by CrossAlchemy** [comment] 2015-02-05 15:39
Same with firefox, after flash plugin update.
flash ver is 16.0.0.305

**Comment by twistedjoe** [comment] 2015-02-05 16:09
Thanks for the report, is it one of the sample or can you confirm one of the sample does not work ( probably the thread one (sample 9) by the look of it) ? I doubt I'll be able to work on it before march, but I'll try to give it a look.

**Comment by CrossAlchemy** [comment] 2015-02-05 16:23
I'm sure it does not work. Did you see where stack is leads to?
global/C_Run::newThread()
from simple call of pthread_create.
i think that worker does not start at all.
These problems come with 16.0.0.305
Simply call pthread_create with valid arguments and see what will happen..

**Comment by CrossAlchemy** [comment] 2015-02-05 16:46
Hell, what does it mean ?
https://bugbase.adobe.com/index.cfm?event=selectBug&CFGRIDKEY=3378018

**Comment by CrossAlchemy** [comment] 2015-02-05 17:07
I compiled example 09
tried to run it and here it is
ArgumentError: Error #3735
ArgumentError: Error #3735
	at global/C_Run::newThread()
	at com.adobe.flascc::CModule$/startBackground()
	at com.adobe.flascc::Console/init()
	at com.adobe.flascc::Console()
	at com.adobe.flascc.preloader::DefaultPreloader/onPreloaderComplete()

**Comment by vpmedia** [comment] 2015-02-06 07:21
Hi!
I'll try to look into the issue in the forthcoming days - but I've to note if threading worked in previous FlashPlayer versions it's possible that the problem is out of CrossBridge SDK scope and maybe related to the core FP development.
You can check the related CrossBridge source code here:
https://github.com/crossbridge-community/crossbridge/blob/master/posix/C_Run.as
https://github.com/crossbridge-community/crossbridge/blob/master/posix/PlayerCreateWorker.as

**Comment by CrossAlchemy** [comment] 2015-02-06 07:31
Workers do work, i checked.
i think these hacks are too dirty function retargetSWF():ByteArray
It seems like adobe is now marking bytearrays or may be crc check.
retargetSWF() - that causing troubles.

**Comment by CrossAlchemy** [comment] 2015-02-06 07:37
So if im right then AlcSprite has no use now.
We need to dispatch threads in console.

**Comment by vpmedia** [comment] 2015-02-06 07:51
I'm not sure.. If retargetSWF stopped working (crc check or similar) that would mean a lot of 3rd party libs are also broke (like as3swf, easyWorkers - which all utilizes runtime swf bytearray assembling).

**Comment by CrossAlchemy** [comment] 2015-02-06 08:05
Try to answer a simple question
Who needs them.
I think correct work of consoled swfs has critical priority comparing to swc
imho

**Comment by vpmedia** [comment] 2015-02-11 12:45
If I'm correct this ticket duplicates #77 (Both related to threading error 3735)

**Comment by CrossAlchemy** [comment] 2015-02-11 13:14
yep, you are right

**Comment by vpmedia** [comment] 2015-02-11 15:53
closing as duplicate.

**Closed by vpmedia** 2015-02-11 15:53 UTC
